spring:
  datasource:
    # 数据库访问配置, 使用druid数据源(默认数据源是HikariDataSource)
    type: com.alibaba.druid.pool.DruidDataSource
    #链接池配置
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.3.137:3306/bizwms1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=America/Los_Angeles&useAffectedRows=true&useLegacyDatetimeCode=false
#      url: jdbc:mysql://127.0.0.1:3306/bizapp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=America/Los_Angeles&useAffectedRows=true&useLegacyDatetimeCode=false
#      url: jdbc:mysql://52.13.251.120:3306/bizapp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B10&useAffectedRows=true&useLegacyDatetimeCode=false
      username: root
      password: root
#      password: 7CY2Ra29T9181m9

      # 连接池配置：大小，最小，最大
      initial-size: 50
      min-idle: 50
      max-active: 2000

      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接，间隔时间
      time-between-eviction-runs-millis: 60000

      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      # 检测连接是否有，有效得select语句
      validation-query: select '1' from dual
      # 申请连接的时候检测，如果空闲时间大于time-between-eviction-runs-millis，执行validationQuery检测连接是否有效，建议配置为true，不影响性能，并且保证安全性。
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，建议设置为false，不然会会降低性能
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，建议设置为false，不然会会降低性能
      test-on-return: false

      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20

      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙防御sql注入，stat监控统计,logback日志
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      #aop-patterns: com.springboot.servie.*
      # lowSqlMillis用来配置SQL慢的标准，执行时间超过slowSqlMillis的就是慢
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

      # WebStatFilter监控配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则：那些访问拦截统计
        url-pattern: /*
        # 忽略过滤的格式：哪些不拦截，不统计
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置（Druid监控后台的Servlet映射配置，因为SpringBoot项目没有web.xml所在在这里使用配置文件设置）
      stat-view-servlet:
        enabled: true
        # 配置Servlet的访问路径：访问路径为/druid/**时，跳转到StatViewServlet，会自动转到Druid监控后台
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 设置监控后台的访问账户及密码
        login-username: xsge
        login-password: xsge
        # IP白名单：允许哪些主机访问，默认为“”任何主机
        # allow: 127.0.0.1
        # IP黑名单：禁止IP访问，（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true
      keep-alive: true
      max-evictable-idle-time-millis: 400000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
#  mail:
#    # 配置 SMTP 服务器地址
#    host: smtp.gamil.com
#    # 发送者邮箱
#    username: noreply@bizblockusa.com
#    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
#    password: gF9Kpt3AMZZJ
#    # 端口号465或587
#    port: 465
#    # 默认的邮件编码为UTF-8
#    default-encoding: UTF-8
#    # 配置SSL 加密工厂
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          socketFactoryClass: javax.net.ssl.SSLSocketFactory
#        ssl:
#          enable: true
#        display:
#          sendmail: Source
#          sendname: suzuka
#        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
#        debug: true
#    protocol: smtp

server:
  port: 18823
  undertow:
    threads:
      io: 32
      worker: 256
    buffer-size: 1024
    direct-buffers: true
mybatis:
  # 配置别名
  type-aliases-package: com.example.order.pojo
  # 配置XML扫描地址
  mapper-locations:
    - classpath:mapper/*.xml
  # 配置启用驼峰命名方式
  configuration:
    map-underscore-to-camel-case: false
    #    sql语句打印到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    default-executor-type: simple
    default-statement-timeout: 25000
    call-setters-on-nulls: true
#    interceptors: com.github.pagehelper.PageInterceptor
# 设置日志显示：在控制台打印SQL
#logging:
#  level:
#    # 以包名前置，表示指定包下的操作指定日志级别。
#    com.xsge.app.mapper: DEBUG

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#debug: true
